### ISSUE TITLE
What type of url to enter in the code

### ISSUE THREAD

**Issue by shikaismaru** [Rotzke/fetlife#2]
Hi Rotzke,
Thanks for the code, I was trying to use it, the problem is that I don't know what url I should enter, I got an account on fetlife and tried different urls of groups/profile/city but I always get an empty csv file, just with the titles and no datas.
And in the python script I get 
------------------------------ MENU ------------------------------
1. Generate members list
2. Exit
------------------------------------------------------------------
Enter your choice [1-2]: 1

Copy URL and press any key...https://fetlife.com/groups/3899
2018-08-25 12:31:21,322 | INFO: Parser initialization...OK
2018-08-25 12:31:21,328 | INFO: Starting new HTTPS connection (1): fetlife.com

2018-08-25 12:31:24,082 | INFO: Parsed last page! Exiting...

Would appreciate if you could help.
Thanks

**Comment by shikaismaru** [comment]
I found out that we just need to find the right page with the list of profiles.
It works.
Thanks

**Comment by Rotzke** [comment]
@shikaismaru No problems :D

**Comment by BrownyInSales** [comment]
Is this broken? 
I am having the same issue.
Entering either the group page or the group member page yeilds a blank CSV
Any pointers would be great.

**Comment by Rotzke** [comment]
@BrownyInSales I have updated the stuff to latest version, now it is even cooler, enjoy. It is now using another library to parse HTML, so check `requirements.txt` and new comments in (shit)code.

**Comment by BrownyInSales** [comment]
Working successfully on Apple Mac installing with Brew with minor changes to the direct path:
`
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

ser = Service("/usr/local/bin/chromedriver")

driver = webdriver.Chrome(service=ser, options=options)

`

and to:

` 
username = driver.find_element(By.ID, "user_login")
password = driver.find_element(By.ID, "user_password")
driver.find_element(By.XPATH, '//button').click()

`

PS: Thank you! (I found them...)
